# Generated by Django 4.1.1 on 2023-03-31 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(max_length=50)),
                ('ship_IMO', models.CharField(max_length=7)),
                ('ship_description', models.CharField(max_length=500)),
                ('ship_status', models.CharField(default=0, max_length=1)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2023, 3, 31, 4, 3, 38, 760326, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
